/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const header_Logic = require('./code/header-logic');
const items_Logic = require('./code/items-logic');
const itemdetails_Logic = require('./code/itemdetails-logic');
const itemattributes_Logic = require('./code/itemattributes-logic');
const notes_Logic = require('./code/notes-logic');

class ccm_dashboard_mockSrv extends LCAPApplicationService {
    async init() {

        this.on('READ', 'Header', async (request, next) => {
            await header_Logic(request);
            return next();
        });

        this.on('READ', 'Items', async (request, next) => {
            await items_Logic(request);
            return next();
        });

        this.on('READ', 'ItemDetails', async (request, next) => {
            await itemdetails_Logic(request);
            return next();
        });

        this.on('READ', 'ItemAttributes', async (request, next) => {
            await itemattributes_Logic(request);
            return next();
        });

        this.on('READ', 'Notes', async (request, next) => {
            await notes_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    ccm_dashboard_mockSrv
};